name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 📦 Use Node.js v16.14.2 (LTS)
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Start
      run: npm start
    - name: Run tests
      run: npm test
    - name: Build
      run: npm build